language: ruby

rvm:
  - 1.9.2
  - 1.9.3

env:
  - DB=redis

services:
  - redis-server

script:
  - bundle exec rspec spec --tag ~@defer --order random
  - bundle exec rspec spec --tag  @defer --order random
